# Default values for ssu-aad-ephemeral-uri-updater.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
managedByHelm: true
environment: "develop"

app:
  config:
    configSecretRef: ssu-ephemeral-environments-config
  env:
    - name: SAEUU_URIPREFIX
      value: http://localhost:8080/REPLACEME/
    - name: SAEUU_AZUREREDIRECTURI
      value: http://localhost:8080/setup/return
    - name: SAEUU_WORKERINTERVAL
      value: "10"

image:
  repository: 905418183222.dkr.ecr.eu-west-1.amazonaws.com/ssu-aad-ephemeral-uri-updater
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  match: Host(`localhost`)
  prefixMiddleware:
    enabled: true
    prefix: /replaceme
  middlewares: []
  services: []
  routes: []
    # - kind: Rule
    #   match: Host(`build.dfds.cloud`)
    #   priority: 90
    #   middlewares: []
    #   services:
    #     - kind: Service
    #       name: ssu-aad-ephemeral-uri-updater
    #       namespace: selfservice
    #       port: external

resources:
  requests:
    memory: "20Mi"
    cpu: "50m"
  limits:
    memory: "100Mi"
    cpu: "100m"


nodeSelector: {}

tolerations: []

affinity: {}
