apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssu-aad-ephemeral-uri-updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssu-aad-ephemeral-uri-updater.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: http
  selector:
    {{- include "ssu-aad-ephemeral-uri-updater.selectorLabels" . | nindent 4 }}
